dist: xenial #с этого года по дефолту
sudo: required

language: cpp

os:
  - linux

compiler:
  - gcc
  
before_install:
  - chmod +x build.sh

install:
- source ci/travis/install-linux.sh

script:
  - mkdir build
  - cd build
  - cmake ..
  - make

notifications:
  email:
    - laciedreamer@gmail.com
