dist: bionic s
sudo: enabled

language: cpp

os:
  - linux
#  - osx

compiler:
  - gcc
  - clang
#before_install:
#  - chmod +x ci/travis/install-linux.sh

before_install:
  - sudo apt update
  - sudo apt install make
  - sudo apt install libboost-all-dev
  - sudo apt install sqlite3

  - git clone https://github.com/abseil/googletest.git
  - cd googletest/
  - git submodule update --init
  - mkdir build
  - cd build
  - cmake ..
  - make -j8
  - sudo make install
  - cd ../..

install:
  - skip

script:
  - mkdir build
  - cd build
  - cmake ..
  - make

notifications:
  email:
    - laciedreamer@gmail.com
