dist: bionic s
sudo: enabled

language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  exclude:
  - os:       osx
    compiler: gcc

install:
- source ci/travis/install-$TRAVIS_OS_NAME.sh

script:
  - mkdir build
  - cd build
  - cmake ..
  - make

notifications:
  email:
    - laciedreamer@gmail.com
