dist: xenial #с этого года по дефолту
sudo: required

language: cpp

os:
  - linux

compiler:
  - gcc

install:
  - skip

script:
  - mkdir build
  - cd build
  - cmake ..
  - make

notifications:
  email:
    - laciedreamer@gmail.com
